version: 0.2
 
batch:
   fast-fail: false
   build-fanout:
     parallelism: 1
     ignore-failure: false
 
phases:
   install:
     commands:
       - echo 'Install dependencies'
       - composer require --dev phpunit/phpunit
   pre_build:
     commands:
       - echo 'prebuild'
   build:
     commands:
       - echo 'Running phpunit Tests'
       - composer dump-autoload
       - codebuild-tests-run --test-command "./vendor/bin/phpunit -vv" --files-search "codebuild-glob-search '**/*Test.php'"

   post_build:
       commands:
         - echo 'Test execution completed'
